name: Continuous Integration
on: [push, pull_request]

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        version: [ '7.1', '7.2', '7.3', '7.4', '8.0', '8.1' ]
      fail-fast: false
    steps:
      - uses: actions/checkout@master
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.version }}
          coverage: xdebug2
      - run: composer install --dev ${{ matrix.flags }}
      - run: vendor/bin/atoum
